# Generated by Django 5.2 on 2025-04-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='_encrypted_employee_id',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
