# Generated by Django 4.2.10 on 2025-04-23 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee__encrypted_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='roles',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='duties',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='end_dates',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_dates',
            field=models.DateTimeField(),
        ),
    ]
