# Generated by Django 4.2.10 on 2025-04-26 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_employee_department'),
        ('employees', '0002_alter_employeehistory_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehistory',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_set', to='companies.department'),
        ),
    ]
