# Generated by Django 4.2.10 on 2025-04-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_departments_remove_employee_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='end_dates',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_dates',
            field=models.DateField(),
        ),
    ]
