# Generated by Django 4.2.10 on 2025-04-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_end_dates_alter_employee_start_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='duties',
            field=models.TextField(),
        ),
    ]
