# Generated by Django 5.2 on 2025-04-06 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='_encrypted_contact_person',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='_encrypted_email',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='_encrypted_phone',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='_encrypted_registration_number',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='employee_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
