# Generated by Django 4.2.10 on 2025-04-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
