# Generated by Django 4.2.10 on 2025-04-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_department_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='departments',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
