# Generated by Django 5.2 on 2025-04-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='departments',
            field=models.TextField(),
        ),
    ]
